### PR TITLE
Manage gitlab groups

### PR DESCRIPTION
**Pull request by Xx-Parks-xX**
Contribute to #6

### CODE REVIEW

**Comment by clarsonneur** [comment]
Looks to work in progress, right?

**Comment by Xx-Parks-xX** [comment]
> Looks to work in progress, right?

Yes not finished

**Comment by clarsonneur** [comment]
ok

**Comment by Xx-Parks-xX** [comment]
Feature finished, the main objective is reached. For more, I need to contribute to another project (go gitlab)

**Comment by clarsonneur** [comment]
Good work @Xx-Parks-xX !

**Pull request merged**
